name: PR Build

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  setup-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: NPM Install
        run: npm ci
      - name: Lint
        run: cd packages/ts-query-model && npm run lint
      - name: Run Unit Tests
        run: cd packages/ts-query-model && npm run test
  integration-test-mysql:
    name: MySQL integration tests
    needs: setup-and-test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    services:
      mysql:
        image: mysql
        ports:
          - 3306:3306
        env:
          MYSQL_DATABASE: query-test
          MYSQL_USER: query-test
          MYSQL_PASSWORD: query-test
          MYSQL_ROOT_PASSWORD: query-test
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure NPM cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
      - name: Seed database
        run: |
          cat packages/integration-test/fixtures/mysql/test-db-seed.sql | mysql -uquery-test -pquery-test -h127.0.0.1 query-test
      - name: Install packages
        run: |
          npm ci
      - name: Run integration tests
        run: |
          cd packages/integration-test
          npm run test
